# Generated by Django 5.1.7 on 2025-03-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('scientific_name', models.CharField(default='', max_length=100)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('watering_frequency', models.FloatField(choices=[(0.000694, 'Debug (1 min)'), (1, 'Daily'), (2, 'Every 2 days'), (7, 'Weekly'), (14, 'Bi-weekly'), (30, 'Monthly')], default=7, help_text='How often the plant should be watered')),
                ('last_watered', models.DateField(blank=True, help_text='When the plant was last watered', null=True)),
            ],
        ),
    ]
