# Generated by Django 5.1.7 on 2025-03-15 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='last_watered',
            field=models.DateField(blank=True, help_text='When the plant was last watered', null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='scientific_name',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plant',
            name='watering_frequency',
            field=models.FloatField(choices=[(0.000694, 'Debug (1 min)'), (1, 'Daily'), (2, 'Every 2 days'), (7, 'Weekly'), (14, 'Bi-weekly'), (30, 'Monthly')], default=7, help_text='How often the plant should be watered'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
