# Generated by Django 5.1.7 on 2025-03-16 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='scientific_name',
            new_name='botanical_name',
        ),
    ]
