# Generated by Django 5.1.7 on 2025-03-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0002_rename_scientific_name_plant_botanical_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='last_watered',
            field=models.DateTimeField(blank=True, help_text='When the plant was last watered', null=True),
        ),
    ]
