# Generated by Django 5.1.7 on 2025-03-18 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0003_alter_plant_last_watered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='watering_frequency',
            field=models.IntegerField(choices=[(1, 'DEBUG (1 hr)'), (24, 'Daily'), (48, 'Every 2 days'), (168, 'Weekly'), (336, 'Bi-weekly'), (672, 'Monthly')], default=168, help_text='How often the plant should be watered'),
        ),
    ]
