# Generated by Django 5.1.7 on 2025-03-18 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0004_alter_plant_watering_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='harvest_months',
            field=models.CharField(choices=[('JAN', 'January'), ('FEB', 'February'), ('MAR', 'March'), ('APR', 'April'), ('MAY', 'May'), ('JUN', 'June'), ('JUL', 'July'), ('AUG', 'August'), ('SEP', 'September'), ('OCT', 'October'), ('NOV', 'November'), ('DEC', 'December')], default='', max_length=50),
        ),
    ]
