# Generated by Django 5.1.7 on 2025-03-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0005_plant_harvest_months'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='harvest_months',
            field=models.CharField(default='', max_length=200),
        ),
    ]
