# Generated by Django 5.1.7 on 2025-03-18 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0006_alter_plant_harvest_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='base_color',
            field=models.CharField(default='#7f9261', max_length=7),
        ),
    ]
