# Generated by Django 5.1.7 on 2025-03-18 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0007_plant_base_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='botanical_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
